<?php
/**
 * Title: Featured Product
 * Slug: online-fashion/featured-product
 * Categories: online-fashion
 *
 * @package Online Fashion
 * @since 1.0.0
 */

?>

<!-- wp:group {"metadata":{"name":"Featured Products"},"style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50"}}},"className":"animated fadeInUp","layout":{"type":"constrained"}} -->
<div class="wp-block-group animated fadeInUp" style="padding-top:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50)"><!-- wp:heading {"textAlign":"left","style":{"typography":{"fontSize":"32px","fontStyle":"normal","fontWeight":"700"},"spacing":{"margin":{"bottom":"var:preset|spacing|30"}}},"fontFamily":"noto-sans-lao"} -->
<h2 class="wp-block-heading has-text-align-left has-noto-sans-lao-font-family" style="margin-bottom:var(--wp--preset--spacing--30);font-size:32px;font-style:normal;font-weight:700"><?php echo esc_html__( 'Hidden Gems', 'online-fashion' ); ?></h2>
<!-- /wp:heading -->
<?php if (function_exists('wc_booster_load') && class_exists('WooCommerce')) { ?>
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|30"}}}} -->
<div class="wp-block-columns"><!-- wp:column {"width":"25%"} -->
<div class="wp-block-column" style="flex-basis:25%"><!-- wp:wc-booster/call-to-action {"block_id":"wc-booster-cta-block-adddca92-bcb2-4ea8-b057-ebf3fa724ab7","bgImage":{"size":"full","id":890,"alt":"cta image 1","url":"<?php echo esc_url( get_template_directory_uri() );?>/assets/images/img2.png","height":1824,"width":1705,"sizes":{"thumbnail":{"height":150,"width":150,"url":"<?php echo esc_url( get_template_directory_uri() );?>/assets/images/img2.png","orientation":"landscape"}}},"bgColor":"#fc5b62","heading":"Shop Your <mark style=\"background-color:rgba(0, 0, 0, 0);color:#00dcff\" class=\"has-inline-color\">Heart </mark>Out With Us","subDescription":"","subDescriptionColor":"#eeeeee","headingColor":"#ffffff","overlay":"#b23209","borderRadius":10,"contentWidth":{"activeUnit":"%","range":{"min":1,"max":100},"values":{"desktop":100,"tablet":100,"mobile":100},"responsiveViews":["desktop","tablet","mobile"],"units":["%"]},"headingTypo":{"fontFamily":"","fontSize":{"units":["px","em","rem"],"activeUnit":"px","values":{"desktop":24,"tablet":32,"mobile":26},"range":{"min":0,"max":100}},"fontWeight":"800","lineHeight":{"activeUnit":"","units":[""],"values":{"desktop":1.5,"tablet":1,"mobile":1},"range":{"min":0,"max":100}},"textTransform":""}} -->
<!-- wp:buttons {"align":"left","layout":{"type":"flex","justifyContent":"left"},"style":{"spacing":{"blockGap":"0"}},"fontSize":"small"} -->
<div class="wp-block-buttons has-custom-font-size has-small-font-size"><!-- wp:button {"textColor":"base-2","style":{"elements":{"link":{"color":{"text":"var:preset|color|base-2"}}},"spacing":{"padding":{"left":"var:preset|spacing|30","right":"var:preset|spacing|30","top":"8px","bottom":"8px"}},"color":{"background":"#1002ed"}},"className":"is-style-fill"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link has-base-2-color has-text-color has-background has-link-color wp-element-button" style="background-color:#1002ed;padding-top:8px;padding-right:var(--wp--preset--spacing--30);padding-bottom:8px;padding-left:var(--wp--preset--spacing--30)"><?php echo esc_html__( 'Buy Now', 'online-fashion' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
<!-- /wp:wc-booster/call-to-action -->

<!-- wp:wc-booster/call-to-action {"block_id":"wc-booster-cta-block-d1674c96-1e35-4af2-b958-65070aebb35a","bgImage":{"size":"full","id":1360,"alt":"cta image 2","url":"<?php echo esc_url( get_template_directory_uri() );?>/assets/images/img6.png","height":2214,"width":1826,"sizes":{"thumbnail":{"height":150,"width":150,"url":"<?php echo esc_url( get_template_directory_uri() );?>/assets/images/img6.png","orientation":"landscape"}}},"bgColor":"#fc5b62","heading":"Buy <mark style=\"background-color:rgba(0, 0, 0, 0);color:#12ff04\" class=\"has-inline-color\">2 </mark>Get 1 <mark style=\"background-color:rgba(0, 0, 0, 0);color:#00f603\" class=\"has-inline-color\">Free</mark>","subDescription":"","subDescriptionColor":"#eeeeee","alignment":"right","headingColor":"#ffffff","overlay":"#02304a","borderRadius":10,"contentWidth":{"activeUnit":"%","range":{"min":1,"max":100},"values":{"desktop":64,"tablet":100,"mobile":100},"responsiveViews":["desktop","tablet","mobile"],"units":["%"]},"headingTypo":{"fontFamily":"","fontSize":{"units":["px","em","rem"],"activeUnit":"px","values":{"desktop":24,"tablet":32,"mobile":26},"range":{"min":0,"max":100}},"fontWeight":"800","lineHeight":{"activeUnit":"","units":[""],"values":{"desktop":1.5,"tablet":1,"mobile":1},"range":{"min":0,"max":100}},"textTransform":""},"contentAlignment":"right"} -->
<!-- wp:buttons {"align":"left","layout":{"type":"flex","justifyContent":"right"},"style":{"spacing":{"blockGap":"0"}},"fontSize":"small"} -->
<div class="wp-block-buttons has-custom-font-size has-small-font-size"><!-- wp:button {"textColor":"base-2","style":{"elements":{"link":{"color":{"text":"var:preset|color|base-2"}}},"spacing":{"padding":{"left":"var:preset|spacing|30","right":"var:preset|spacing|30","top":"8px","bottom":"8px"}},"color":{"background":"#00a1eb"}},"className":"is-style-fill"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link has-base-2-color has-text-color has-background has-link-color wp-element-button" style="background-color:#00a1eb;padding-top:8px;padding-right:var(--wp--preset--spacing--30);padding-bottom:8px;padding-left:var(--wp--preset--spacing--30)"><?php echo esc_html__( 'Buy Now', 'online-fashion' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
<!-- /wp:wc-booster/call-to-action --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"75%"} -->
<div class="wp-block-column" style="flex-basis:75%"><!-- wp:wc-booster/carousel-product {"block_id":"wc-booster-carousel-product-block-4d06c583-99a7-4cbe-be80-d084379d4c0c","postsToShow":4,"order":"asc","titleTypo":{"fontFamily":"","fontSize":{"units":["px","em","rem"],"activeUnit":"px","values":{"desktop":15,"tablet":20,"mobile":20},"range":{"min":0,"max":100}},"fontWeight":"500","lineHeight":{"activeUnit":"px","units":["px"],"values":{"desktop":28,"tablet":28,"mobile":28}}},"metaTypo":{"fontFamily":"","fontSize":{"units":["px","em","rem"],"activeUnit":"px","values":{"desktop":11,"tablet":12,"mobile":12},"range":{"min":0,"max":100}},"fontWeight":400,"lineHeight":{"activeUnit":"","units":[""],"values":{"desktop":1.2,"tablet":1.2,"mobile":1.2}}},"priceTypo":{"fontFamily":"","fontSize":{"units":["px","em","rem"],"activeUnit":"px","values":{"desktop":14,"tablet":17,"mobile":17},"range":{"min":0,"max":100}},"fontWeight":400,"lineHeight":{"activeUnit":"","units":[""],"values":{"desktop":1.2,"tablet":1.2,"mobile":1.2}}},"buttonTypo":{"fontFamily":"","fontSize":{"units":["px","em","rem"],"activeUnit":"px","values":{"desktop":14,"tablet":17,"mobile":17},"range":{"min":0,"max":100}},"fontWeight":"300","lineHeight":{"activeUnit":"","units":[""],"values":{"desktop":1.2,"tablet":1.2,"mobile":1.2}}},"buttonMargin":{"activeUnit":"px","isLinkActive":false,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","rem"],"values":{"desktop":[20,0,20,0],"tablet":[23,0,15,0],"mobile":[23,0,15,0]}},"buttonTextColor":"#9f1616","buttonBackground":"transparent","padding":{"activeUnit":"px","isLinkActive":true,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","rem"],"values":{"desktop":[0,0,0,0],"tablet":[20,20,20,20],"mobile":[20,20,20,20]}},"productMargin":{"activeUnit":"px","isLinkActive":false,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","rem"],"values":{"desktop":[12,15,0,15],"tablet":[0,15,0,15],"mobile":[0,15,0,15]}},"productPadding":{"activeUnit":"px","isLinkActive":true,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","rem"],"values":{"desktop":[0,0,0,0],"tablet":[0,0,15,0],"mobile":[0,0,15,0]}},"enableButton":true,"imageSize":"woocommerce_thumbnail","slidesToShow":{"activeUnit":"","range":{"min":1,"max":10},"values":{"desktop":5,"tablet":2,"mobile":1},"units":[""]},"wrapperTarget":false,"autoplay":true,"pauseOnHover":true,"enableArrow":false} /-->

<!-- wp:wc-booster/carousel-product {"block_id":"wc-booster-carousel-product-block-c67ea90f-eca4-4ba7-8cb0-182b32700535","postsToShow":4,"titleTypo":{"fontFamily":"","fontSize":{"units":["px","em","rem"],"activeUnit":"px","values":{"desktop":15,"tablet":20,"mobile":20},"range":{"min":0,"max":100}},"fontWeight":"500","lineHeight":{"activeUnit":"px","units":["px"],"values":{"desktop":28,"tablet":28,"mobile":28}}},"metaTypo":{"fontFamily":"","fontSize":{"units":["px","em","rem"],"activeUnit":"px","values":{"desktop":11,"tablet":12,"mobile":12},"range":{"min":0,"max":100}},"fontWeight":400,"lineHeight":{"activeUnit":"","units":[""],"values":{"desktop":1.2,"tablet":1.2,"mobile":1.2}}},"priceTypo":{"fontFamily":"","fontSize":{"units":["px","em","rem"],"activeUnit":"px","values":{"desktop":14,"tablet":17,"mobile":17},"range":{"min":0,"max":100}},"fontWeight":400,"lineHeight":{"activeUnit":"","units":[""],"values":{"desktop":1.2,"tablet":1.2,"mobile":1.2}}},"buttonTypo":{"fontFamily":"","fontSize":{"units":["px","em","rem"],"activeUnit":"px","values":{"desktop":14,"tablet":17,"mobile":17},"range":{"min":0,"max":100}},"fontWeight":"300","lineHeight":{"activeUnit":"","units":[""],"values":{"desktop":1.2,"tablet":1.2,"mobile":1.2}}},"buttonMargin":{"activeUnit":"px","isLinkActive":false,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","rem"],"values":{"desktop":[20,0,20,0],"tablet":[23,0,15,0],"mobile":[23,0,15,0]}},"buttonTextColor":"#9f1616","buttonBackground":"transparent","padding":{"activeUnit":"px","isLinkActive":true,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","rem"],"values":{"desktop":[0,0,0,0],"tablet":[20,20,20,20],"mobile":[20,20,20,20]}},"productMargin":{"activeUnit":"px","isLinkActive":false,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","rem"],"values":{"desktop":[12,15,0,15],"tablet":[0,15,0,15],"mobile":[0,15,0,15]}},"productPadding":{"activeUnit":"px","isLinkActive":true,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","rem"],"values":{"desktop":[0,0,0,0],"tablet":[0,0,15,0],"mobile":[0,0,15,0]}},"enableButton":true,"imageSize":"woocommerce_thumbnail","slidesToShow":{"activeUnit":"","range":{"min":1,"max":10},"values":{"desktop":5,"tablet":2,"mobile":1},"units":[""]},"wrapperTarget":false,"autoplay":true,"pauseOnHover":true,"enableArrow":false} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
<?php } ?>
</div>
<!-- /wp:group -->